# Site Settings
paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at

defaults:
  -
    scope:
      path: '' # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true  # Change it to be 'false', can close the comments of a post separately.
      toc: true # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: tags
    values:
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      is_tab: true
      breadcrumb:
        -
          label: Home
          url: /

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
  path: rss-feed.xml

timezone: Asia/Shanghai

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor/ # Avoid Jekyll mitankenly read and explode on the Travis vender directory.
  - scripts/
  - Gemfile.lock
  - Gemfile
  - assets/css/src/
  - assets/js/src/
  - assets/js/dist/commons/

blocklist:
  - /norobots/
  - /assets/
  - /tabs/
  - /categories/
  - /tags/
