# The Site Settings
# © 2017-2019 Cotes Chung
# MIT licensed

baseurl: '' # if your site type is Project Pages in GitHub Pages, change it to '/projectname'

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""        # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true  # Enable comments in posts.
      toc: true       # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      dynamic_title: true # hide title in mobile screens.
      breadcrumb:
        -
          label: Home
          url: /

timezone: Asia/Shanghai

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

jekyll_timeago:
  depth: 1
  default_locale: 'en'
  fallbacks: true

exclude:
  - vendor/       # Avoid Jekyll mistakenly read the vender directory in Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - run.sh
  - build.sh

sitemap_exclude:  # Sitemap will exclude the following items.
  - /norobots/
  - /assets/
  - /tabs/
  - /categories/
  - /tags/
  - /posts/
  - /404.html
  - /redirects.json
  - /search.json
