google-ID: 'your_google_id'

disqus-shortname: 'your_disqus_shortname'

publication-date: 2017  # The Site's first publication date.

version: 2.8  # Current site version.

url: 'http://localhost:4000' # Replace with your domain