title: 'The Site Name'
slogan: "The slogan to your site."
description: "The site description." # RSS feed
logo: "/assets/img/sample/ant.png"

comments: true  # ture - enable, false - disable

lang: en # Must be 'en' or 'zh'

tabs:
  - { name: {zh: '首页', en: 'Home'}}
  - { name: {zh: '分类', en: 'Categories'}, path: 'tabs', url: 'categories'}
  - { name: {zh: '标签', en: 'Tags'}, path: 'tabs', url: 'tags'}
  - { name: {zh: '归档', en: 'Archives'}, path: 'tabs', url: 'archives'}
  - { name: {zh: '关于', en: 'About'}, path: 'tabs', url: 'about'}
